numpy: vektor = sorvektor
=============

Érdemes így felfogni sztem. :)

In [2]:
from __future__ import print_function
import numpy as np

In [3]:
m = np.arange(25).reshape(5,5)
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
v = np.array([0,0,10,100,-100])
print(v)

[   0    0   10  100 -100]


In [5]:
# sorvektorként broadcastolja
x = m + v
print(x)

[[  0   1  12 103 -96]
 [  5   6  17 108 -91]
 [ 10  11  22 113 -86]
 [ 15  16  27 118 -81]
 [ 20  21  32 123 -76]]


In [6]:
w = v[:, None] # ua: w = v[:, np.newaxis] -- oszlopvektorrá alakítás
print(w)

[[   0]
 [   0]
 [  10]
 [ 100]
 [-100]]


In [7]:
# oszlopvektor broadcast
y = m + w
print(y)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 20  21  22  23  24]
 [115 116 117 118 119]
 [-80 -79 -78 -77 -76]]


In [8]:
z = v + w # broadcast 2x
print(z)

[[   0    0   10  100 -100]
 [   0    0   10  100 -100]
 [  10   10   20  110  -90]
 [ 100  100  110  200    0]
 [-100 -100  -90    0 -200]]
